name: vality
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
